title = "GeeKoffee"
baseURL = "https://geekoffee.ml/"
languageCode = "en-us"
theme = "terminal"
disqusShortname = "geekoffee"
copyright = "© 2019 Glauber Magalhaes.&nbsp;<a href=\"https://www.gnu.org/licenses/gpl-3.0.html\">Some rights reserved</a>."

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  author = "Glauber Magalhães"
  
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  
  # set theme to full screen width
  fullWidthTheme = false
  
  # center theme with default width
  centerTheme = false
  
  # set a custom favicon (default is a `themeColor` square)
  favicon = "/favicon.png"

[languages]
  [languages.en]
    title = "GeeKoffee"
    subtitle = "Programming tips & blog"
    keywords = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "› GeeKoffee"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About me"
        url = "/pages/about"